name: mypy

on:
  push:
  pull_request:
    branches:
      - 'shihe/TMINFRA-380**'

jobs:
  my-py-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        ls
        python -m pip install --upgrade pip
        pip install mypy
    - name: Analysing the code with mypy
      run: | 
        mypy @scripts/path_to_check.txt --config-file scripts/mypy.ini