name: mypy-newcheck

on:
  push:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - development

jobs:
  optional-static-type-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
    - name: check changed files
      uses: tj-actions/changed-files@v18.7 # ref: https://github.com/tj-actions/changed-files
      id: changed-files-specific # this id can be used below
      with: 
        files_from_source_file:  # source file(s) used to populate the files input
          .github/mypy/path_to_check.txt
    - name: generate mypy report # report for path_to_check rather than changed files
      continue-on-error: true
      run: |
        mypy @.github/mypy/path_to_check.txt
    - name: show report
      run: |
        cat any-exprs.txt
    - name: Analyzing the code with mypy
      id: mypy-check
      if: steps.changed-files-specific.outputs.any_changed == 'true' # only file changed will trigger Analyzing
      run: | 
        mypy ${{ steps.changed-files-specific.outputs.all_changed_files }} --config-file mypy.ini
