name: mypy[experiments]

on:
  pull_request:
    branches:
      - development

jobs:
  optional-static-type-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        pip install lxml
    - name: check changed files
      uses: tj-actions/changed-files@v18.7 # ref: https://github.com/tj-actions/changed-files
      id: changed-files-specific # this id can be used below
      with: 
        files_from_source_file:  # source file(s) used to populate the files input
          .github/mypy/path_to_check.txt
    - name: generate mypy report # report for path_to_check rather than changed files
      id: generate-report
      continue-on-error: true
      run: |
        mypy @.github/mypy/path_to_check.txt
    - name: upload report
      id: upload-report
      run: |
        tar -cvzf report.tar.gz index.html mypy-html.css html
        curl -u admin:${{secrets.NEXUS_PASSWORD}} --upload-file report.tar.gz "http://drone.glid.to:8081/repository/glide-artifacts/mypy-report-${GITHUB_RUN_ID}/"
        echo "You can download report from below link"
        echo "http://drone.glid.to:8081/repository/glide-artifacts/mypy-report-${GITHUB_RUN_ID}/report.tar.gz"
        echo "test http://www.baidu.com"
    - name: Analyzing the code with mypy
      id: mypy-check
      if: steps.changed-files-specific.outputs.any_changed == 'true' # only file changed will trigger Analyzing
      run: | 
        mypy ${{ steps.changed-files-specific.outputs.all_changed_files }}
